#!/usr/bin/env perl

use strict;
use warnings;
use Carp;
use Getopt::Long qw(:config posix_default no_ignore_case bundling pass_through);
use FindBin;
use lib("$FindBin::Bin/PerlLib");
use Pipeliner;

my $VERSION = 0.1.0;

my $help_flag;

## required opts
my $left_fq;
my $right_fq;
my $chimeric_junctions;
my $aligned_bam;
my $output_dir;

## optional
my $genome_lib_dir = $ENV{CTAT_GENOME_LIB};
my $CPU = 4;
my $SHOW_FULL_USAGE_INFO = 0;

## GMAP-fusion options
my $MIN_TRANS_LEN_TRY_CHIM = 30;
my $MIN_J = 1;
my $MIN_SUM_JS = 2;
my $MIN_NOVEL_J = 3;
my $SPLIT_BREAKPOINT_EXTEND_LENGTH = 25;
my $MAX_FUZZY_OVERLAP = 12;

my $SHOW_VERSION = 0;

my $usage = <<__EOUSAGE;

################################################################
#
#  Required:
#
#  --left_fq <string>    reads_1.fq
#
#  --right_fq <string>   reads_2.fq
#
#  --chimeric_junctions <string>  STAR Chimeric.out.junction file
#                        
#  --aligned_bam <string>         STAR aligned bam file
#                        
#  --output_dir STR_OUT_DIR          output directory
#                        
#
# Optional:
#
#  --genome_lib_dir <string>  directory for CTAT genome lib  (or use env var \$CTAT_GENOME_LIB
#                                      current setting: ($ENV{CTAT_GENOME_LIB})
#  --CPU <int>                     :number threads (default $CPU)
#
#  --show_full_usage_info     flag, shows all options available.
#
################################################################

__EOUSAGE

    ;


my $additional_usage_info = <<__EXTRA_USAGE;
#  Additional parameters:
#
#  --min_chim_len|L <int>            :minimum length for a chimeric alignment (default: $MIN_TRANS_LEN_TRY_CHIM)
#
#  --min_J|J <int>                 :minimum number of junction frags (default: $MIN_J)  
#
#  --min_sumJS|S <int>             :minimum sum (junction + spanning) frags (default: $MIN_SUM_JS)
#
#  --min_novel_junction_support <int>   :minimum number of junction reads required for novel (non-reference) exon-exon junction support.
#                                        (default: $MIN_NOVEL_J)
#  --split_breakpoint_extend_length <int>   :in assessing breakpoint quality, the length to extend each split sequence beyond
#                                           the proposed breakpoint. (default: $SPLIT_BREAKPOINT_EXTEND_LENGTH)
#
#  --max_fuzzy_overlap <int>               :maximum allowed overlap of extended length from breakpoint (default: $MAX_FUZZY_OVERLAP)
#
#  
#############################################################################################


__EXTRA_USAGE
    
;


&GetOptions ( 'h' => \$help_flag,

              ## Required
              'left_fq=s' => \$left_fq,
              'right_fq=s' => \$right_fq,

              'chimeric_junctions=s' => \$chimeric_junctions,

              'aligned_bam=s' => \$aligned_bam,
              'output_dir=s' => \$output_dir,
              
              ## Optional
              'genome_lib_dir=s' => \$genome_lib_dir,
              'CPU=i' => \$CPU,
              'show_full_usage_info' => \$SHOW_FULL_USAGE_INFO,
              
              ## gmap-fusion opts
              'min_chim_len|L=i' => \$MIN_TRANS_LEN_TRY_CHIM,
              'min_J=i' => \$MIN_J,
              'min_sumJS=i' => \$MIN_SUM_JS,
              'min_novel_junction_support=i' => \$MIN_NOVEL_J,
              'split_breakpoint_extend_length=i' => \$SPLIT_BREAKPOINT_EXTEND_LENGTH,
              'max_fuzzy_overlap=i' => \$MAX_FUZZY_OVERLAP,
              
              'version' => \$SHOW_VERSION,
              
);


if ($SHOW_FULL_USAGE_INFO) {
    $usage .= $additional_usage_info;
    die $usage;
}

if ($help_flag) {
    die $usage;
}


if ($SHOW_VERSION) {
    print "\n\tTrinityFusion v$VERSION\n\n";
}

unless($left_fq && $right_fq && $chimeric_junctions && $aligned_bam && $output_dir && $genome_lib_dir) {
    die $usage;
}


# set full paths for all inputs
$left_fq = &Pipeliner::ensure_full_path($left_fq);
$right_fq = &Pipeliner::ensure_full_path($right_fq);
$chimeric_junctions = &Pipeliner::ensure_full_path($chimeric_junctions);
$aligned_bam = &Pipeliner::ensure_full_path($aligned_bam);
$output_dir = &Pipeliner::ensure_full_path($output_dir);
$genome_lib_dir = &Pipeliner::ensure_full_path($genome_lib_dir);

my $DISCASM = $FindBin::Bin . "/DISCASM/DISCASM";
my $GMAP_FUSION = $FindBin::Bin . "/GMAP-fusion/GMAP-fusion";


main: {
     
    if (! -d $output_dir) {
        &Pipeliner::process_cmd("mkdir -p $output_dir");
    }
    chdir($output_dir) or die "Error, cannot cd to $output_dir";

    my $chkpts_dir = "$output_dir/__chkpts";
    my $pipeliner = new Pipeliner( '-checkpoint_dir' => $chkpts_dir );
    
    ## run DISCASM
    my $cmd = "$DISCASM "
        . " --chimeric_junctions $chimeric_junctions "
        . " --aligned_bam $aligned_bam "
        . " --left_fq $left_fq "
        . " --right_fq $right_fq "
        . " --out_dir trinity_discasm "
        . " --denovo_assembler Trinity ";

    $pipeliner->add_commands(new Command($cmd, "discasm.ok"));

    ## run GMAP-fusion
    $cmd = "$GMAP_FUSION -T trinity_discasm/trinity_out_dir/Trinity.fasta"
        . " --genome_lib_dir $genome_lib_dir "
        . " --left_fq $left_fq "
        . " --right_fq $right_fq "
        . " --CPU $CPU "
        . " -L $MIN_TRANS_LEN_TRY_CHIM "
        . " --min_J $MIN_J "
        . " --min_sumJS $MIN_SUM_JS "
        . " --min_novel_junction_support $MIN_NOVEL_J "
        . " --split_breakpoint_extend_length $SPLIT_BREAKPOINT_EXTEND_LENGTH "
        . " --max_fuzzy_overlap $MAX_FUZZY_OVERLAP ";

    $pipeliner->add_commands(new Command($cmd, "gmap-fusion.ok"));
    
    $pipeliner->run();

    exit(0);
}

        
